#!/usr/bin/env python3
"""
시뮬레이션용 ArUco 마커 텍스처 PNG 생성 스크립트.

실행 (최초 1회, Gazebo 실행 전):
    python3 gazebo/gen_aruco_model.py

결과:
    gazebo/models/aruco_marker_0/materials/textures/aruco_0.png
"""
import os
import sys

try:
    import cv2
    import cv2.aruco as aruco
    import numpy as np
except ImportError:
    print("ERROR: opencv-python 이 설치되지 않았습니다.")
    print("       pip3 install opencv-python")
    sys.exit(1)

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
adict = aruco.getPredefinedDictionary(aruco.DICT_4X4_50)

# 400 px code + 60 px quiet zone per side = 520 px, so the printed plane is
# always code_size * 520/400.  Keep this ratio: the detector's marker_size_m is
# the BLACK CODE, not the plane, and range scales linearly with it.
CODE_PX, BORDER_PX = 400, 60

# Two markers, because one cannot cover the whole descent.  The visible radius
# r(h) = h*tan(vfov/2) - s/2 goes to zero at h = s/(2 tan(vfov/2)), which for
# the 1.5 m marker in the gimbal camera is 0.97 m — above the 0.25 m touchdown
# height, so the last 0.72 m was flown blind.  h_blind scales with marker size,
# so a small marker AT THE LANDING POINT closes the gap (0.25 m -> 0.16 m).
# The small one has to be at the centre, not beside the big one: at h = 0.3 m
# the camera only sees a 0.23 m radius, so anything offset is already gone.
# A small marker CANNOT literally sit inside a big one: DICT_4X4_50 is 4x4 data
# plus a 1-cell border = 6 cells, so over a 1.5 m code each cell is 0.25 m and a
# 0.39 m inner plane wipes the middle 2x2 — data bits — and the big marker stops
# decoding.  So the pattern is made SYMMETRIC about the landing point instead:
# two big markers flanking a small one, all concentric with the deck centre.
MARKERS = (
    (0, "big   long-range, deck (-1.10, 0)"),
    (2, "big   long-range, deck (+1.10, 0)"),
    (1, "small near-field centring, deck centre"),
)

for marker_id, role in MARKERS:
    name = f"aruco_marker_{marker_id}"
    tex_dir = os.path.join(SCRIPT_DIR, "models", name, "materials", "textures")
    os.makedirs(tex_dir, exist_ok=True)

    marker = aruco.generateImageMarker(adict, marker_id, CODE_PX)
    bordered = cv2.copyMakeBorder(marker, BORDER_PX, BORDER_PX,
                                  BORDER_PX, BORDER_PX,
                                  cv2.BORDER_CONSTANT, value=255)
    out = os.path.join(tex_dir, f"aruco_{marker_id}.png")
    cv2.imwrite(out, bordered)

    config = os.path.join(SCRIPT_DIR, "models", name, "model.config")
    if not os.path.exists(config):
        with open(config, "w") as f:
            f.write(f"""<?xml version="1.0"?>
<model>
  <name>{name}</name>
  <version>1.0</version>
  <sdf version="1.9">model.sdf</sdf>
  <description>
    ArUco DICT_4X4_50 ID={marker_id} texture ({role}).
    Generated by gazebo/gen_aruco_model.py — see MARKERS there.
  </description>
</model>
""")
        print(f"  + wrote {config}")

    print(f"✓ ID={marker_id} ({role}): {out}  "
          f"{bordered.shape[1]}×{bordered.shape[0]} px")

print("\n  plane size = code_size * 520/400, e.g. 1.50 m code -> 1.95 m plane,")
print("               0.25 m code -> 0.325 m plane.")
print("  이제 ./gazebo/run_gimbal.sh 로 실행하면 두 마커가 월드에 나타납니다.")
