#!/usr/bin/env python3
"""
시뮬레이션용 ArUco 마커 텍스처 PNG 생성 스크립트.

실행 (최초 1회, Gazebo 실행 전):
    python3 simulation/gazebo/gen_aruco_model.py

결과:
    simulation/gazebo/models/aruco_marker_0/materials/textures/aruco_0.png
"""
import os
import sys

try:
    import cv2
    import cv2.aruco as aruco
except ImportError:
    print("ERROR: opencv-python 이 설치되지 않았습니다.")
    print("       pip3 install opencv-python")
    sys.exit(1)

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
adict = aruco.getPredefinedDictionary(aruco.DICT_4X4_50)

# 400 px code + 60 px quiet zone per side = 520 px, so the printed plane is
# always code_size * 520/400.  Keep this ratio: the detector's marker_size_m is
# the BLACK CODE, not the plane, and range scales linearly with it.
CODE_PX, BORDER_PX = 400, 60

# Three markers cover the descent: two mirrored 1.30 m long-range codes and a
# centred 0.30 m near-field code.  Their detector offsets all resolve to the
# same deck-centre landing point.
MARKERS = (
    (0, "big   long-range, deck (-1.10, 0)"),
    (2, "big   long-range, deck (+1.10, 0)"),
    (1, "small near-field centring, deck centre"),
)

for marker_id, role in MARKERS:
    name = f"aruco_marker_{marker_id}"
    tex_dir = os.path.join(SCRIPT_DIR, "models", name, "materials", "textures")
    os.makedirs(tex_dir, exist_ok=True)

    if hasattr(aruco, "generateImageMarker"):
        marker = aruco.generateImageMarker(adict, marker_id, CODE_PX)
    else:
        marker = aruco.drawMarker(adict, marker_id, CODE_PX)
    bordered = cv2.copyMakeBorder(marker, BORDER_PX, BORDER_PX,
                                  BORDER_PX, BORDER_PX,
                                  cv2.BORDER_CONSTANT, value=255)
    out = os.path.join(tex_dir, f"aruco_{marker_id}.png")
    cv2.imwrite(out, bordered)

    config = os.path.join(SCRIPT_DIR, "models", name, "model.config")
    if not os.path.exists(config):
        with open(config, "w") as f:
            f.write(f"""<?xml version="1.0"?>
<model>
  <name>{name}</name>
  <version>1.0</version>
  <sdf version="1.9">model.sdf</sdf>
  <description>
    ArUco DICT_4X4_50 ID={marker_id} texture ({role}).
    Generated by simulation/gazebo/gen_aruco_model.py — see MARKERS there.
  </description>
</model>
""")
        print(f"  + wrote {config}")

    print(f"✓ ID={marker_id} ({role}): {out}  "
          f"{bordered.shape[1]}×{bordered.shape[0]} px")

print("\n  plane size = code_size * 520/400: 1.30 m -> 1.69 m,")
print("               0.30 m -> 0.39 m.")
print("  이제 ./simulation/gazebo/run_gimbal.sh 로 실행하면 세 마커가 나타납니다.")
